import React from 'react';
import { StyleSheet } from 'react-native';
import MaterialCommunityIcons from 'react-native-vector-icons/MaterialCommunityIcons';

export const getIcon = (name: string): React.ReactNode => {
  return <MaterialCommunityIcons name={name} size={26} color="#fa0" />;
};

export const tabTheme = {
  dark: true,
  colors: {
    primary: '#fa0',
    background: '#222',
    card: '#222',
    text: '#fa0',
    border: '#444',
    notification: '#fa0',
  },
};

export const styles = StyleSheet.create({
  progressView: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#222',
    height: 20,
  },
  container: {
    flex: 1,
    padding: 4,
    backgroundColor: '#222',
    color: '#fa0',
    textAlignVertical: 'center',
    textTransform: 'uppercase',
    verticalAlign: 'middle',
  },
  actionBarView: {
    paddingTop: 4,
    paddingBottom: 4,
    height: 50,
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    verticalAlign: 'middle',
    textTransform: 'uppercase',
    textAlignVertical: 'center',
    backgroundColor: '#222',
  },
  actionBarHeader: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignContent: 'flex-end',
    alignItems: 'flex-end',
    fontSize: 30,
    color: '#fa0',
    textAlign: 'left',
    fontWeight: '300',
    textTransform: 'uppercase',
  },
  actionBarButton: {
    borderCurve: 'continuous',
    backgroundColor: '#222',
    borderColor: '#fa0',
    borderWidth: 1,
    textAlign: 'right',
    color: '#fa0',
    fontSize: 18,
    alignSelf: 'flex-end',
    alignContent: 'flex-end',
    alignItems: 'flex-end',
    textAlignVertical: 'center',
    textTransform: 'uppercase',
    verticalAlign: 'middle',
    width: 90,
    shadowColor: '#fa0',
  },
  actionBarButtonRunning: {
    borderCurve: 'continuous',
    backgroundColor: '#fa0',
    borderColor: '#fa0',
    borderWidth: 1,
    textAlign: 'right',
    color: '#222',
    fontSize: 18,
    alignSelf: 'flex-end',
    alignContent: 'flex-end',
    alignItems: 'flex-end',
    textAlignVertical: 'center',
    textTransform: 'uppercase',
    verticalAlign: 'top',
    width: 90,
  },
  redColor: {
    color: '#f22',
  },
  greenColor: {
    color: '#2f2',
  },
  actionBarStatusIcon: {
    backgroundColor: '#222',
    fontSize: 26,
    textTransform: 'uppercase',
    marginHorizontal: 10,
    padding: 4,
  },
  button: {
    borderCurve: 'continuous',
    backgroundColor: '#fa0',
    textAlign: 'right',
    color: '#222',
    fontSize: 18,
    alignSelf: 'flex-end',
    alignContent: 'flex-end',
    alignItems: 'flex-end',
    textAlignVertical: 'center',
    textTransform: 'uppercase',
    verticalAlign: 'top',
  },
  centerContainer: {
    flex: 1,
    padding: 16,
    justifyContent: 'center',
    alignItems: 'flex-end',
    textAlign: 'right',
    backgroundColor: '#222',
    verticalAlign: 'middle',
  },
  heading: {
    fontSize: 22,
    fontWeight: 'normal',
    color: '#fa0',
    flexWrap: 'wrap',
    textTransform: 'uppercase',
    alignItems: 'flex-end',
    textAlign: 'right',
    alignContent: 'flex-end',
  },
  text: {
    fontSize: 22,
    fontWeight: '200',
    color: '#fa0',
    textTransform: 'uppercase',
    alignItems: 'flex-end',
    textAlign: 'right',
    alignContent: 'flex-end',
  },
  textSmall: {
    fontSize: 14,
    color: '#fa0',
    textTransform: 'uppercase',
    alignItems: 'flex-end',
    textAlign: 'right',
    alignContent: 'flex-end',
  },
  sensorItem: {
    padding: 12,
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    backgroundColor: '#222',
    borderBottomColor: '#444',
    textTransform: 'uppercase',
    borderBottomWidth: 1,
  },
  sensorTitle: {
    fontSize: 30,
    fontWeight: '200',
    textTransform: 'uppercase',
    minWidth: 100,
    color: '#fa0',
  },
  sensorValue: {
    fontSize: 36,
    textTransform: 'uppercase',
    textAlign: 'right',
    fontWeight: 'normal',
    flexGrow: 1,
    color: '#fa0',
  },
  infoItem: {
    paddingHorizontal: 12,
    paddingVertical: 2,
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    backgroundColor: '#222',
    borderColor: '#444',
    textTransform: 'uppercase',
    borderTopWidth: 1,
  },
  infoTitle: {
    paddingHorizontal: 4,
    fontSize: 16,
    fontWeight: '200',
    textTransform: 'uppercase',
    textAlign: 'right',
    minWidth: 100,
    color: '#fa0',
  },
  infoValue: {
    paddingHorizontal: 4,
    fontSize: 16,
    textTransform: 'uppercase',
    textAlign: 'left',
    fontWeight: 'normal',
    flexGrow: 1,
    color: '#fa0',
  },
  sensorUnit: {
    fontSize: 18,
    fontWeight: '300',
    textAlign: 'right',
    textTransform: 'uppercase',
    minWidth: 50,
    color: '#fa0',
  },
  statusText: {
    padding: 30,
    fontSize: 16,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    color: '#fa0',
  },
});
